#!/usr/bin/php
<?php

require_once __DIR__ . '/../../vendor/autoload.php';
require_once __DIR__ . '/BuildEntity.php';

use Symfony\Component\Console\Application;
use EntityForge\EntityGenerator\BuildEntity as EntityBuilder;


class CommandBuilder extends Application {
    public function __construct(){
        parent::__construct();
        $this->add(new EntityBuilder());
        $this->run();
    }
}

new CommandBuilder();
